Models/PanchayatActivity.cs
using Microsoft.Data.SqlClient;
using System.Data;
using System.Diagnostics;

namespace Panchayat.Models
{
    public class PanchayatActivity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }

        public static void AddActivities(PanchayatActivity activity)
        {
            SqlConnection conn = new SqlConnection();
            conn.ConnectionString = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=cdac;Integrated Security=True";
            conn.Open();
            try
            {
                SqlCommand cmd = conn.CreateCommand();
                cmd.CommandType = CommandType.Text;
                cmd.CommandText = $"insert into PanchayatActivities(Name, Description, Date) values(@Name, @Description, @Date)";
                cmd.Parameters.AddWithValue("@Name", activity.Name);
                cmd.Parameters.AddWithValue("@Description", activity.Description);
                cmd.Parameters.AddWithValue("@Date", activity.Date);
                cmd.ExecuteNonQuery();
            }
            catch (Exception ex)
            {

            }
            finally { conn.Close(); }
        }

        public static List<PanchayatActivity> GetAllActivities()
        {
            SqlConnection conn = new SqlConnection();
            conn.ConnectionString = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=cdac;Integrated Security=True";
            List<PanchayatActivity> list = new List<PanchayatActivity>();
            conn.Open();
            try
            {
                SqlCommand cmd = conn.CreateCommand();
                cmd.CommandType = CommandType.Text;
                cmd.CommandText = "select * from PanchayatActivities";
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    list.Add(new PanchayatActivity { Id = (int)dr["Id"], Name = (string)dr["Name"], Description = (string)dr["Description"], Date = (string)dr["Date"] });
                }

                return list;

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return null;
            }
            finally { conn.Close(); }
        }
        public static PanchayatActivity GetActivityById(int id)
        {
            SqlConnection conn = new SqlConnection();
            conn.ConnectionString = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=cdac;Integrated Security=True";
            conn.Open();
            try
            {
                SqlCommand cmd = conn.CreateCommand();
                cmd.CommandType = CommandType.Text;
                cmd.CommandText = $"select * from PanchayatActivities where Id ={id}";
                SqlDataReader dr = cmd.ExecuteReader();
                dr.Read();
                PanchayatActivity activity = new PanchayatActivity();
                activity.Id = (int)dr["Id"];
                activity.Name = (string)dr["Name"];
                activity.Description = (string)dr["Description"];
                activity.Date = (string)dr["Date"];
                return activity;
            }
            catch (Exception ex)
            {
                return null;
            }
            finally { conn.Close(); }
        }
        public static void UpdateActivity(int id, PanchayatActivity activity)
        {
            SqlConnection conn = new SqlConnection();
            conn.ConnectionString = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=cdac;Integrated Security=True";
            conn.Open();
            try
            {
                SqlCommand cmd = conn.CreateCommand();
                cmd.CommandType = CommandType.Text;
                cmd.CommandText = $"update PanchayatActivities set Name = '{activity.Name}', Description = '{activity.Description}', Date = '{activity.Date}' where Id ={id}";
                cmd.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                
            }
            finally { conn.Close(); }

        }
        public static void DeleteActivity(int id)
        {
            SqlConnection conn = new SqlConnection();
            conn.ConnectionString = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=cdac;Integrated Security=True";
            conn.Open();
            try
            {
                SqlCommand cmd = conn.CreateCommand();
                cmd.CommandType = CommandType.Text;
                cmd.CommandText = $"delete from PanchayatActivities where Id ={id}";
                cmd.ExecuteNonQuery();
            }
            catch (Exception ex)
            {

            }
            finally { conn.Close(); }
        }
    }
}

Controllers/PanchayatActivitiesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Panchayat.Models;

namespace Panchayat.Controllers
{
    public class PanchayatActivitiesController : Controller
    {
        // GET: PanchayatController
        public ActionResult Index()
        {
            List<PanchayatActivity> list = PanchayatActivity.GetAllActivities();
            return View(list);
        }
        public ActionResult AdminPage()
        {
            return View();
        }
        public ActionResult ActivitiesForUser()
        {
            List<PanchayatActivity> list = PanchayatActivity.GetAllActivities();
            return View(list);
        }

        // GET: PanchayatController/Details/5
        public ActionResult Details(int id)
        {
            PanchayatActivity activity = PanchayatActivity.GetActivityById(id); 
            return View(activity);
        }
        public ActionResult ActivityDetailsForUser(int id)
        {
            PanchayatActivity activity = PanchayatActivity.GetActivityById(id); 
            return View(activity);
        }

        // GET: PanchayatController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PanchayatController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PanchayatActivity activity)
        {
            try
            {
                PanchayatActivity.AddActivities(activity);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PanchayatController/Edit/5
        public ActionResult Edit(int id)
        {
            PanchayatActivity activity = PanchayatActivity.GetActivityById(id);
            return View(activity);
        }

        // POST: PanchayatController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PanchayatActivity activity)
        {
            try
            {
                PanchayatActivity.UpdateActivity(id, activity);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PanchayatController/Delete/5
        public ActionResult Delete(int id)
        {
            PanchayatActivity activity = PanchayatActivity.GetActivityById(id);
            return View(activity);
        }

        // POST: PanchayatController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, PanchayatActivity activity)
        {
            try
            {
                PanchayatActivity.DeleteActivity(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/RaiseFundsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Panchayat.Models;

namespace Panchayat.Controllers
{
    public class RaiseFundsController : Controller
    {
        // GET: RaiseFundsController
        public ActionResult Index()
        {
            List<RaiseFund> list = RaiseFund.GetAllDonations();
            return View(list);
        }

        // GET: RaiseFundsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RaiseFundsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RaiseFundsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RaiseFund fund)
        {
            try
            {
                RaiseFund.AddFund(fund);
                return RedirectToAction(nameof(Create));
            }
            catch
            {
                return View();
            }
        }

        // GET: RaiseFundsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RaiseFundsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RaiseFundsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RaiseFundsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/SignupsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Panchayat.Models;

namespace Panchayat.Controllers
{
    public class SignupsController : Controller
    {
        // GET: SignupsController
        public ActionResult Index()
        {
            List<Signup> list = Signup.getAllSignups();
            return View(list);
        }

        // GET: SignupsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SignupsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SignupsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Signup signup)
        {
            try
            {
                Signup.AddUserInSignup(signup);
                return RedirectToAction(nameof(Login));
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Login()
        {
            return View();
        }

        // POST: SignupsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Signup signup)
        {
            try
            {
                bool status = Signup.VerifyUser(signup);
                if (status)
                {
                    return RedirectToAction(nameof(Index));

                }
                else
                return RedirectToAction(nameof(Create));
            }
            catch
            {
                return View();
            }
        }

        // GET: SignupsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SignupsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SignupsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SignupsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/PanchayatActivities/ActivitiesForUser.cshtml
@model IEnumerable<Panchayat.Models.PanchayatActivity>

@{
    ViewData["Title"] = "ActivitiesForUser";
}

<h3 class="text-center mt-5"><span class="text-light shadow rounded-3 bg-success p-2">Activities</span></h3>

<div class="row mt-5 justify-content-center">
    <div class="col-sm-12 col-md-5 d-flex">

        @foreach (var item in Model)
        {
            <div class="card ms-2 shadow me-2" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">@Html.DisplayFor(modelItem => item.Name)</h5>
                    <div>
                        <a asp-controller="PanchayatActivities" asp-action="ActivityDetailsForUser" class="text-decoration-none">@Html.ActionLink("Read more...", "ActivityDetailsForUser", new { item.Id }, new{@class = "text-decoration-none"})</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div class="d-flex justify-content-center mt-5 ">
    <button style="width:120px" class="btn btn-secondary shadow"><a class="text-decoration-none text-light" asp-controller="Signups" asp-action="Index">Back</a></button>
</div>

Views/PanchayatActivities/ActivityDetailsForUser.cshtml
@model Panchayat.Models.PanchayatActivity

@{
    ViewData["Title"] = "ActivityDetailsForUser";
}

<h3 class=" text-center mt-5"><span class="text-light shadow rounded-3 bg-success p-2" >Activity Details</span></h3>

<div class="row mt-5 justify-content-center">
    <div class="col-sm-12 col-md-3 d-flex">
        <div class="card ms-2 shadow" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">@Html.DisplayFor(model => model.Name)</h5>
                <p class="card-text">@Html.DisplayFor(model => model.Description)</p>
                <div>
                    <a class="text-decoration-none text-secondary ">@Html.DisplayFor(model => model.Date)</a>
                </div>
                <button class="form-control bg-secondary mt-2">
                <a class="text-decoration-none text-light" asp-action="ActivitiesForUser">Back</a>
                </button>
            </div>
        </div>
    </div>
</div>

Views/PanchayatActivities/AdminPage.cshtml
@model IEnumerable<Panchayat.Models.Signup>

@{
    ViewData["Title"] = "AdminPage";
}

<div class="row justify-content-center mt-5">
    <div class="col-sm-12 col-md-4 mt-5">
        <a class="text-decoration-none text-dark" asp-controller="RaiseFunds" asp-action="Index">
            <div class="card shadow" style="width: 18rem;">
                <img src="~/Images/raisefund.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                    <p class="card-text text-center fs-5">Donations</p>
                </div>
            </div>
        </a>
    </div>
    <div class="col-sm-12 col-md-4 mt-5">
        <a asp-controller="PanchayatActivities" asp-action="Index" class="text-decoration-none text-dark">
            <div class="card shadow" style="width: 18rem;">
                <img src="~/Images/activity.jpg" class="card-img-top raisefund" alt="...">
                <div class="card-body">
                    <p class="card-text text-center fs-5">Add Activities</p>
                </div>
            </div>
        </a>
    </div>
</div>
@*<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>
*@

Views/PanchayatActivities/Create.cshtml
@model Panchayat.Models.PanchayatActivity

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>PanchayatActivity</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Activity name :</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="form-control text-light mt-2 bg-primary" />
            </div>
            <button class="form-control bg-secondary mt-1">
                <a class="text-decoration-none text-light" asp-action="Index">Back</a>
            </button>
        </form>
    </div>
</div>

<div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/PanchayatActivities/Delete.cshtml
@model Panchayat.Models.PanchayatActivity

@{
    ViewData["Title"] = "Delete";
}



<h3 class="text-danger">Are you sure you want to delete this?</h3>
<div>

    <table class="styled-table">
        <thead>
            <tr>
                <th>Activity No</th>
                <th>Activity Name</th>
                <th>Description</th>
                <th>Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.Id)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Name)
                </td>
                <td style="width : 500px">
                    @Html.DisplayFor(model => model.Description)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Date)
                </td>
                <td>
                    <form asp-action="Delete">
                        <input type="submit" value="Delete" class="btn btn-danger" />
                        <button class="btn btn-secondary">
                            <a class="text-decoration-none text-light" asp-action="Index">Back</a>
                        </button>
                    </form>
                </td>
            </tr>
        </tbody>
    </table>
    <dl class="row">
    </dl>

</div>

Views/PanchayatActivities/Details.cshtml
@model Panchayat.Models.PanchayatActivity

@{
    ViewData["Title"] = "Details";
}

<h1 class="text-success">Details</h1>

<div>
    <table class="styled-table">
        <thead>
            <tr>
                <th>Activity No</th>
                <th>Activity Name</th>
                <th>Description</th>
                <th>Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.Id)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Name)
                </td>
                <td style="width : 500px">
                    @Html.DisplayFor(model => model.Description)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Date)
                </td>
                <td>
                    <button class="btn btn-success">
                    @Html.ActionLink("Edit", "Edit", new { Model.Id }, new {@class = "text-decoration-none text-light" })
                    </button>
                    <button class="btn btn-secondary shadow">
                        <a class="text-decoration-none text-light" asp-action="Index">Back</a>
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</div>

Views/PanchayatActivities/Edit.cshtml
@model Panchayat.Models.PanchayatActivity

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-success text-center mt-5">Update Activity</h1>

<div class="row mt-5 justify-content-center">
    <div class="col-md-4 shadow-lg p-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="form-control mt-2 shadow text-light bg-primary" />
            </div>
            <button class="form-control bg-secondary mt-2">
                <a class="text-decoration-none text-light shadow" asp-action="Index">Back</a>
            </button>
        </form>
    </div>
</div>

<div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/PanchayatActivities/Index.cshtml
@model IEnumerable<Panchayat.Models.PanchayatActivity>

@{
    ViewData["Title"] = "Index";
}

<h3 class="text-center mt-5"><span class="bg-success shadow p-2 rounded-3 text-light">Activities</span></h3>

<div class="row justify-content-center">

    <table class="styled-table">
        <thead>
            <tr>
                <th>
                    Activity No
                </th>
                <th>
                    Activity Name
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td style="width:500px">
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        <button class="btn btn-success">
                            @Html.ActionLink("Edit", "Edit", new { item.Id }, new{@class = "text-light text-decoration-none"})
                        </button>
                        <button class="btn btn-warning">
                            @Html.ActionLink("Details", "Details", new { item.Id }, new{@class = "text-light text-decoration-none"})
                        </button>
                        <button class="btn btn-danger">
                            @Html.ActionLink("Delete", "Delete", new { item.Id }, new{@class = "text-light text-decoration-none"})
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="d-flex justify-content-center">
    <button style="width:120px" class="btn btn-primary me-2">
        <a class="text-decoration-none text-light" asp-action="Create">Add Activity</a>
    </button>
    <button style="width:120px" class="btn btn-secondary"><a class="text-decoration-none text-light" asp-controller="PanchayatActivities" asp-action="AdminPage">Back</a></button>
</div>